<?php
/**
 * Step 4 - import the ZnoteX schema.
 *
 * Only the znote_* tables. Every statement in znote_schema.sql is
 * CREATE TABLE IF NOT EXISTS, so running this against a database that already
 * has some of them adds the missing ones and leaves the rest alone.
 */

if (!defined('ZNOTE_INSTALL')) { http_response_code(403); die('Direct access denied.'); }

$schemaFile = install_root() . '/SQL/znote_schema.sql';
$report     = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {

	$link = install_connect($connectError);

	if ($link === null) {
		install_error('Lost the database connection: ' . ih((string)$connectError));
	} elseif (!is_file($schemaFile)) {
		install_error('SQL/znote_schema.sql is missing.');
	} else {

		$sql = (string)file_get_contents($schemaFile);
		$sql = str_replace(array("\r\n", "\r"), "\n", $sql);

		// Strip line comments, then split on ";" at end of line. The file is
		// generated by us and has no procedures or triggers, so this is safe -
		// a general-purpose SQL splitter would be overkill.
		$sql = preg_replace('/^--.*$/m', '', $sql);

		$created = 0;
		$skipped = 0;
		$errors  = array();

		foreach (array_filter(array_map('trim', explode(";\n", $sql))) as $statement) {
			$statement = trim($statement, "; \t\n\r");
			if ($statement === '') {
				continue;
			}

			// Seed rows must not be duplicated on a re-run.
			if (stripos($statement, 'INSERT INTO') === 0) {
				if (preg_match('/INSERT INTO `([a-z_]+)`/i', $statement, $m)) {
					$check = @$link->query('SELECT 1 FROM `' . $m[1] . '` LIMIT 1');
					if ($check !== false && $check->num_rows > 0) {
						$skipped++;
						continue;
					}
				}
			}

			if (@$link->query($statement)) {
				$created++;
			} else {
				$errors[] = $link->error . "\n    in: "
					. substr((string)preg_replace('/\s+/', ' ', $statement), 0, 90);
			}
		}

		// Record the version, which the schema's own INSERT may have skipped.
		@$link->query("UPDATE `znote` SET `version` = '2.0.0'");

		$tablesNow = 0;
		$result = @$link->query("SHOW TABLES LIKE 'znote%'");
		if ($result !== false) {
			$tablesNow = $result->num_rows;
		}

		$link->close();

		$report = array(
			'created' => $created,
			'skipped' => $skipped,
			'errors'  => $errors,
			'tables'  => $tablesNow,
		);

		if (!$errors) {
			install_state(array('schema_done' => true));
			install_max_step(5);
		} else {
			install_error(count($errors) . ' statement(s) failed. The first was: '
				. ih((string)$errors[0]));
		}
	}
}
?>
<h1>Schema</h1>
<p class="lead">
	Creates the <code>znote_*</code> tables in
	<code><?= ih(install_get('sqlDatabase')) ?></code>. Your server's own tables are not touched.
</p>

<?php if ($report === null): ?>

	<div class="info">
		Every statement is <code>CREATE TABLE IF NOT EXISTS</code>, and seed rows are skipped for
		tables that already hold data &mdash; running this on a database that already has some
		ZnoteX tables adds only what is missing.
	</div>

	<form method="post">
		<div class="actions">
			<button class="btn" type="submit">Import the schema</button>
			<a class="btn ghost" href="<?= install_url(3) ?>">Back</a>
		</div>
	</form>

<?php else: ?>

	<?php if (!$report['errors']): ?>
		<p class="good">
			Done. <?= (int)$report['created'] ?> statement<?= $report['created'] === 1 ? '' : 's' ?> ran,
			<?= (int)$report['skipped'] ?> skipped as already populated.
			<?= (int)$report['tables'] ?> <code>znote_*</code> tables are now present.
		</p>
	<?php else: ?>
		<p class="bad"><?= count($report['errors']) ?> statement(s) failed:</p>
		<pre><?php foreach (array_slice($report['errors'], 0, 6) as $e) { echo ih($e), "\n"; } ?></pre>
	<?php endif; ?>

	<div class="actions">
		<?php if (!$report['errors']): ?>
			<a class="btn" href="<?= install_url(5) ?>">Continue</a>
		<?php else: ?>
			<a class="btn ghost" href="<?= install_url(4) ?>">Try again</a>
		<?php endif; ?>
	</div>

<?php endif; ?>
